table CrimeIncidents
	lineageTag: 547917d3-3be2-4a34-9861-c9674d856ef5

	column CCN
		dataType: int64
		formatString: 0
		lineageTag: 4671c309-49fe-464a-b4e3-740dcd30a0f3
		summarizeBy: none
		sourceColumn: CCN

		annotation SummarizationSetBy = User

	column SHIFT
		dataType: string
		lineageTag: 765f4121-1831-4b9f-8369-0d91258b7a34
		summarizeBy: none
		sourceColumn: SHIFT

		annotation SummarizationSetBy = Automatic

	column METHOD
		dataType: string
		lineageTag: 39e379f2-7b90-41ad-87ef-0595e2a8efba
		summarizeBy: none
		sourceColumn: METHOD

		annotation SummarizationSetBy = Automatic

	column OFFENSE
		dataType: string
		lineageTag: 10a5cd49-f18f-4bde-abd1-17ff98a477d5
		summarizeBy: none
		sourceColumn: OFFENSE

		annotation SummarizationSetBy = Automatic

	column BLOCK
		dataType: string
		lineageTag: b2648cf8-aaf1-47c0-a43d-5847a38b47ad
		summarizeBy: none
		sourceColumn: BLOCK

		annotation SummarizationSetBy = Automatic

	column XBLOCK
		dataType: double
		lineageTag: 429d3123-1502-453f-9e8c-977f2e3c76db
		summarizeBy: none
		sourceColumn: XBLOCK

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column YBLOCK
		dataType: double
		lineageTag: f056167d-d47b-4f15-8ab5-c4241cc4638a
		summarizeBy: none
		sourceColumn: YBLOCK

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column WARD
		dataType: int64
		formatString: 0
		lineageTag: 1657141a-2a7a-4a8d-93fe-4369cf30e8c3
		summarizeBy: none
		sourceColumn: WARD

		annotation SummarizationSetBy = User

	column ANC
		dataType: string
		lineageTag: 40cd922c-4863-486e-9c06-845c2c6e58a9
		summarizeBy: none
		sourceColumn: ANC

		annotation SummarizationSetBy = Automatic

	column DISTRICT
		dataType: int64
		formatString: 0
		lineageTag: 5336a378-ef9a-448d-a6bb-558649475c3f
		summarizeBy: none
		sourceColumn: DISTRICT

		annotation SummarizationSetBy = User

	column PSA
		dataType: int64
		formatString: 0
		lineageTag: 7a5df3ed-7f7c-40d1-96e1-772d69f37770
		summarizeBy: none
		sourceColumn: PSA

		annotation SummarizationSetBy = User

	column NEIGHBORHOOD_CLUSTER
		dataType: string
		lineageTag: 6f1cda5c-3b03-4a31-892f-6fd3fdc5ed9c
		summarizeBy: none
		sourceColumn: NEIGHBORHOOD_CLUSTER

		annotation SummarizationSetBy = Automatic

	column BLOCK_GROUP
		dataType: string
		lineageTag: a6738faa-ef75-40d5-912c-7068620dccf2
		summarizeBy: none
		sourceColumn: BLOCK_GROUP

		annotation SummarizationSetBy = Automatic

	column CENSUS_TRACT
		dataType: string
		lineageTag: cb50193b-4e5d-4eef-b819-0cde6aee8659
		summarizeBy: none
		sourceColumn: CENSUS_TRACT

		annotation SummarizationSetBy = Automatic

	column VOTING_PRECINCT
		dataType: string
		lineageTag: 8535aef0-d1c8-44cf-a8fa-17370bd63c31
		summarizeBy: none
		sourceColumn: VOTING_PRECINCT

		annotation SummarizationSetBy = Automatic

	column LATITUDE
		dataType: double
		lineageTag: db6bc25f-ea59-4ca3-8769-a3a1f41e089a
		dataCategory: Latitude
		summarizeBy: sum
		sourceColumn: LATITUDE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LONGITUDE
		dataType: double
		lineageTag: 0f783a2a-84ba-405e-9179-98f51bbe9b68
		dataCategory: Longitude
		summarizeBy: sum
		sourceColumn: LONGITUDE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BID
		dataType: string
		lineageTag: 1f0e8454-7bf4-46bd-93ba-b49b5d984cb0
		summarizeBy: none
		sourceColumn: BID

		annotation SummarizationSetBy = Automatic

	column OBJECTID
		dataType: int64
		formatString: 0
		lineageTag: 342410b1-382a-4adc-9885-efa20671eddc
		summarizeBy: none
		sourceColumn: OBJECTID

		annotation SummarizationSetBy = User

	column REPORT_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5319124d-8d90-4e9e-bc5f-a9f5a94673db
		summarizeBy: none
		sourceColumn: REPORT_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column REPORT_TIME
		dataType: dateTime
		formatString: Long Time
		lineageTag: ea6b28ca-3bb8-455c-b8a4-0759e15fa2cc
		summarizeBy: none
		sourceColumn: REPORT_TIME

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column START_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: e0f24c95-d1c7-47fe-bde1-03be910d7742
		summarizeBy: none
		sourceColumn: START_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column START_TIME
		dataType: dateTime
		formatString: Long Time
		lineageTag: e217715a-1f3f-4292-adb8-d8a0279a41d4
		summarizeBy: none
		sourceColumn: START_TIME

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column END_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: ec157a9e-6a4f-4759-b199-7554a8a64b80
		summarizeBy: none
		sourceColumn: END_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column END_TIME
		dataType: dateTime
		formatString: Long Time
		lineageTag: 1928064b-612d-465d-9c1f-387e998c4f34
		summarizeBy: none
		sourceColumn: END_TIME

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column NEAREST_15M_START_TIME
		dataType: dateTime
		formatString: Long Time
		lineageTag: 544dd845-d642-4463-b0bb-e4a3c6a81e15
		summarizeBy: none
		sourceColumn: NEAREST_15M_START_TIME

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition CrimeIncidents = m
		mode: import
		source =
				let
				    Source = Table.Combine({CrimeIncidents_2023, CrimeIncidents_2024, CrimeIncidents_2025}),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"START_DATE_ONLY", "START_DATE"}, {"END_DATE_ONLY", "END_DATE"}, {"NEAREST_15M_TIME", "NEAREST_15M_START_TIME"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each [START_DATE] >= #date(2023, 1, 1))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

