table dimDate
	lineageTag: 410c4d27-b429-4d5a-8b9b-1211d9564cd6
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 4c24d7ec-2d67-44c9-a933-44523855ad4a
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 55e4b93b-910f-4eeb-a319-4d3dfa547139
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = User

	column Quarter
		dataType: string
		lineageTag: 72b5e6ef-f8fb-4dd2-804d-70ad962a339e
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: fca1b5d0-abaa-48e7-b9a3-a9e82f51f931
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = User

	column 'Month Name'
		dataType: string
		lineageTag: 13e41522-9371-407d-8670-0b64c3ecb324
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 14fd8373-443c-4215-a0a2-cb91dccecaf4
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = User

	column 'Day of Week'
		dataType: int64
		formatString: 0
		lineageTag: 21b8956a-734d-41bd-aa28-82b0c8ceb0ee
		summarizeBy: none
		sourceColumn: Day of Week

		annotation SummarizationSetBy = User

	column 'Day Name'
		dataType: string
		lineageTag: 440166ef-b9aa-47e9-95f6-2bf34ffee81f
		summarizeBy: none
		sourceColumn: Day Name

		annotation SummarizationSetBy = Automatic

	column 'Week of Year'
		dataType: int64
		formatString: 0
		lineageTag: b0e52330-d050-4722-8e40-5486b8f49007
		summarizeBy: none
		sourceColumn: Week of Year

		annotation SummarizationSetBy = User

	column 'ISO Week Number'
		dataType: int64
		formatString: 0
		lineageTag: d5777492-dfcd-47b2-a0c6-e4e65624d71f
		summarizeBy: none
		sourceColumn: ISO Week Number

		annotation SummarizationSetBy = User

	column Year-Quarter
		dataType: string
		lineageTag: 2432ca58-a47a-4c6a-83ea-100a5bf9be8d
		summarizeBy: none
		sourceColumn: Year-Quarter

		annotation SummarizationSetBy = Automatic

	column Year-Month
		dataType: string
		lineageTag: 6768f39e-fd94-4b54-9676-8260bdb0ac93
		summarizeBy: none
		sourceColumn: Year-Month

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: int64
		formatString: 0
		lineageTag: ab66b518-500b-465d-9ed2-a5c6b06d056e
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = User

	column 'Fiscal Quarter'
		dataType: string
		lineageTag: 7a5cbff2-1fc9-4dbd-ba89-389e2ca887ed
		summarizeBy: none
		sourceColumn: Fiscal Quarter

		annotation SummarizationSetBy = Automatic

	column 'Is Weekend'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d488d5ff-c330-4f02-854e-71dcd70ab40f
		summarizeBy: none
		sourceColumn: Is Weekend

		annotation SummarizationSetBy = Automatic

	column 'Days in Month'
		dataType: int64
		formatString: 0
		lineageTag: bf60683b-d27c-4325-b8e7-293a49dee67e
		summarizeBy: none
		sourceColumn: Days in Month

		annotation SummarizationSetBy = User

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 05a0a8b5-925a-403a-a36a-7c3769be7753
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = User

	column 'Month Short'
		dataType: string
		lineageTag: 279de330-d063-46a2-b3e0-90c4ee6a444e
		summarizeBy: none
		sourceColumn: Month Short

		annotation SummarizationSetBy = Automatic

	column 'Day Short'
		dataType: string
		lineageTag: 85591573-0c57-4c87-b09a-f3dbc798a74c
		summarizeBy: none
		sourceColumn: Day Short

		annotation SummarizationSetBy = Automatic

	column 'Day of Year'
		dataType: int64
		formatString: 0
		lineageTag: 12f91ff5-33eb-4949-9876-37e08285cb5c
		summarizeBy: none
		sourceColumn: Day of Year

		annotation SummarizationSetBy = User

	partition dimDate = m
		mode: import
		source = ```
				let
				    // Get min/max dates from existing crime data
				    StartDate = DateTime.Date(List.Min(CrimeIncidents[START_DATE_ONLY])),
				    EndDate = DateTime.Date(List.Max(CrimeIncidents[REPORT_DATE])),
				
				    // Create continuous date sequence
				    DateList = List.Dates(StartDate, Duration.Days(EndDate - StartDate) + 1, #duration(1,0,0,0)),
				    
				    // Convert to table
				    DateTable = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}),
				
				    // Add date components
				    #"Added Year" = Table.AddColumn(DateTable, "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date])), type text),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added Month Name" = Table.AddColumn(#"Added Month", "Month Name", each Date.ToText([Date], "MMMM"), type text),
				    #"Added Month Short" = Table.AddColumn(#"Added Month Name", "Month Short", each Date.ToText([Date], "MMM"), type text),
				    #"Added Day" = Table.AddColumn(#"Added Month Short", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added Day of Week" = Table.AddColumn(#"Added Day", "Day of Week", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added Day Name" = Table.AddColumn(#"Added Day of Week", "Day Name", each Date.ToText([Date], "dddd"), type text),
				    #"Added Day Short" = Table.AddColumn(#"Added Day Name", "Day Short", each Date.ToText([Date], "ddd"), type text),
				    #"Added Week of Year" = Table.AddColumn(#"Added Day Short", "Week of Year", each Date.WeekOfYear([Date]), Int64.Type),
				    #"Added ISO Week Number" = Table.AddColumn(#"Added Week of Year", "ISO Week Number", each Date.WeekOfYear([Date], Day.Monday), Int64.Type),
				    #"Added Year Quarter" = Table.AddColumn(#"Added ISO Week Number", "Year-Quarter", each Text.From([Year]) & "-" & [Quarter], type text),
				    #"Added Year Month" = Table.AddColumn(#"Added Year Quarter", "Year-Month", each Text.From([Year]) & "-" & Text.PadStart(Text.From([Month]), 2, "0"), type text),
				    #"Added Fiscal Year" = Table.AddColumn(#"Added Year Month", "Fiscal Year", each if [Month] >= 7 then [Year] + 1 else [Year], Int64.Type),
				    #"Added Fiscal Quarter" = Table.AddColumn(#"Added Fiscal Year", "Fiscal Quarter", each 
				        if [Month] >= 7 and [Month] <= 9 then "Q1" 
				        else if [Month] >= 10 and [Month] <= 12 then "Q2"
				        else if [Month] >= 1 and [Month] <= 3 then "Q3"
				        else "Q4", type text),
				    #"Added Is Weekend" = Table.AddColumn(#"Added Fiscal Quarter", "Is Weekend", each [Day Name] = "Saturday" or [Day Name] = "Sunday", type logical),
				    #"Added Days in Month" = Table.AddColumn(#"Added Is Weekend", "Days in Month", each Date.DaysInMonth([Date]), Int64.Type),
				    #"Added DateKey" = Table.AddColumn(#"Added Days in Month", "DateKey", each [Year] * 10000 + [Month] * 100 + [Day], Int64.Type),
				    #"Added Day of Year" = Table.AddColumn(#"Added DateKey", "Day of Year", each Date.DayOfYear([Date]), Int64.Type),
				    
				    // Set final column order and types
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Day of Year", {
				        "Date", "DateKey", "Year", "Quarter", "Year-Quarter", "Month", "Month Name", "Month Short", 
				        "Day", "Day of Week", "Day Name", "Day Short", "Day of Year", "Week of Year", "ISO Week Number", 
				        "Year-Month", "Fiscal Year", "Fiscal Quarter", "Is Weekend", "Days in Month"
				    }),
				    
				    #"Changed Types" = Table.TransformColumnTypes(#"Reordered Columns", {
				        {"Date", type date}, {"DateKey", Int64.Type}, {"Year", Int64.Type}, {"Quarter", type text}, 
				        {"Year-Quarter", type text}, {"Month", Int64.Type}, {"Month Name", type text}, {"Month Short", type text},
				        {"Day", Int64.Type}, {"Day of Week", Int64.Type}, {"Day Name", type text}, {"Day Short", type text},
				        {"Day of Year", Int64.Type}, {"Week of Year", Int64.Type}, {"ISO Week Number", Int64.Type},
				        {"Year-Month", type text}, {"Fiscal Year", Int64.Type}, {"Fiscal Quarter", type text},
				        {"Is Weekend", type logical}, {"Days in Month", Int64.Type}
				    })
				in
				    #"Changed Types"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

